In [1]:
from tensorflow import keras
import tensorflow as tf
from keras.models import load_model
import numpy as np  
import pathlib  
from tensorflow.keras.utils import image_dataset_from_directory
from sklearn.metrics import confusion_matrix
import json

#load訓練好的模型路徑
test_model = tf.keras.models.load_model("inceptionV3.025-0.0506.pb")  

#預測圖片路徑
test_data_path = pathlib.Path("C:/小圖片/ord_test")
test_dataset = image_dataset_from_directory(
    test_data_path, 
    image_size=(320, 320),
    batch_size=12,

)

#评估模型 
test_loss, test_acc = test_model.evaluate(test_dataset)
print(f"test acc: {test_acc:.3f}")

#预测模型  
true_labels = []
predicted_labels = []  
for images, labels in test_dataset:
    true_labels.extend(labels.numpy())
    predictions = test_model.predict(images)
    predicted_labels.extend(np.argmax(predictions, axis=1))

conf_matrix = confusion_matrix(true_labels , predicted_labels)  
print('[')
print('\n'.join([f'[{" ".join(str(x) for x in row)}]' for row in conf_matrix]))  
print(']')


Found 200 files belonging to 10 classes.
17/17 [==============================] - 14s 247ms/step - loss: 0.4803 - acc: 0.8350
test acc: 0.835
[
[12 0 0 1 0 0 0 3 2 2]
[0 16 0 0 0 0 0 4 0 0]
[0 0 19 0 0 0 0 1 0 0]
[0 0 0 20 0 0 0 0 0 0]
[0 0 0 0 20 0 0 0 0 0]
[0 0 0 0 0 20 0 0 0 0]
[0 0 0 0 0 0 18 1 0 1]
[0 0 0 1 0 0 0 19 0 0]
[0 0 0 0 0 0 0 3 16 1]
[0 1 0 0 0 1 0 4 7 7]
]
